services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t11s
      POSTGRES_PASSWORD: "MhIgbP8F2lriTiUOll7eYCMeFO_fSw_9"
    volumes:
      - t11s_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "oTiITr8n48HFsaUqSuuDZ7YCM_QIMmvs"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: t11s_test
      POSTGRES_PASSWORD: "AMXD5hi97bk1j2bb2HZPpv00cPfu2S5V"
    volumes:
      - t11s_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "mGHGh59VczaJe8Z1ad3CRiuCoPxseK3v"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  t11s_data:
  t11s_test_data:
